### PR TITLE
Rerandomize

### PR DESCRIPTION
**Pull request by kelseylarson**
Adds rerandomize(), generate(), and balance() options. Together, rerandomize and balance allow for maximum minimum p-value rerandomization.

### CODE REVIEW

**Comment by kelseylarson** [comment]
Sorry, I was only trying to merge this onto my fork and accidentally merged it onto your original one!

**Comment by acarril** [comment]
Hi! No worries... I was checking out the options you wanted to implement,
they look very interesting.

Let me know if you would like any feedback or help. Best,

**Comment by kelseylarson** [comment]
Thanks, I work at IPA and am looking to add a few options for ways that our PIs like to randomize.

**Comment by acarril** [comment]
Cool! Well let me know if I can help... and good luck doing the PIs bidding!

**Comment by kelseylarson** [comment]
Sure will! I really appreciate how well-commented the program is... it's making my job a lot easier.

**Pull request closed without merging**
